# Generated by Django 3.1.6 on 2021-03-05 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo',
            field=models.BooleanField(choices=[(True, 'Usuario'), (False, 'Propietario')], default=True),
        ),
    ]
